version: 1.0.{build}
image: Visual Studio 2019 Preview
build_script:
- ps: >-
    dotnet build src --configuration Release

    dotnet test src --configuration Release --no-build --no-restore
artifacts:
- path: nugets\**\*.nupkg